Add tun post script
xjasonlyu/tun2socks pull request #233
Opened 2023-03-15 03:58 UTC by Jackarain

用于在 tun 设备创建后，执行一个自定义的脚本，比如
```
tun2socks -device tun3 -proxy socks5://127.0.0.1:1080 -postup "/bin/sh /root/proxy/route.sh"
```
route.sh 内容如:
```
# 配置 tun3 的 IP
ip addr add 172.16.8.1/24 dev tun3
ip link set dev tun3 up

# 添加代理服务地址直接通过 pppoe-WAN 路由
route add -host xxx.xxx.xxx.xxx dev pppoe-WAN

# 一些需要通过 tun3 代理的 ip 段...
route add -net 103.235.0.0/16 gw 172.16.8.1
route add -net 117.168.0.0/16 gw 172.16.8.1
route add -net 117.18.0.0/16 gw 172.16.8.1
route add -net 149.154.0.0/16 gw 172.16.8.1
route add -net 185.199.0.0/16 gw 172.16.8.1
```

有了 postup 这个参数，这样用便于做一些 tun 创建之后相关的自己的脚本设定。

2023-03-15 04:56 UTC, xjasonlyu commented
Hi！这个想法我之前有过，不过后来觉得直接集成在里面不够优雅，因为完全可以通过在外部调用解决。

2023-03-15 06:06 UTC, Jackarain commented
是的，外部调用虽然也可以做到。但是拆分成外部调用，会和通过 tun2socks 来调用，这2者用法有很大区别，由其是把 tun2socks 做成系统服务的时候，如果没有这个参数，事情就会变得相对复杂很多。
另外，这可以给人多一个选择，具体用法还取决于用户自己的需求，同样依然可以继续通过外部调用来完成。

2023-03-15 06:42 UTC, xjasonlyu commented
系统服务，例如systemd，可以用`ExecStartPost`处理，反而更加符合设计原理。

2023-03-15 06:55 UTC, Jackarain commented
比如像 sysvinit 并没有像 systemd 的 ExecStartPost 这种功能，还比如 windows 的服务。
当遇到这种情况的时候，只能使用一个专门的壳程序来启动 tun2socks 及 script 并管理进程，像这种结构并不优雅。

2023-03-17 14:47 UTC, xjasonlyu commented
嗯确实有一些道理。不过既然这样的话，应该也提供一个类似于`ExecStartPre`的参数。另外需要注意下代码中的一些规范问题，例如日志应该用专门的`log`模块打印，而不是`fmt.Println`；`pre` 和 `post` 两个功能最好通过不同的func来分开处理等。

2023-03-19 11:30 UTC, Jackarain commented
谢谢你接受了我的提议，并给出代码上的建议。
后面我会按你的建议重新做修改，命名我将参考 `WireGuard` 中类似的功能命名为： `PreUP` 和 `PostUP`，如果你没有意见的话。

2023-03-19 11:38 UTC, xjasonlyu commented
可以，我觉得这个命名不错！

2023-03-20 10:42 UTC, Jackarain commented
Ok，已经完成，有空帮忙 Review

谢谢

2023-03-20 11:38 UTC, xjasonlyu requested changes

2023-03-20 11:38 UTC, xjasonlyu commented on engine/engine.go
> +func preUp(script string) {
- 参数名换成cmd吧，因为不一定是script
- log看看这样：`"[PREUP] failed to execute %s: %v"`

2023-03-20 12:58 UTC, Jackarain commented on engine/engine.go
> +	preUp(k.TunPreUp)
这里似乎不太合适使用 `defer`，因为 `postUp` 的设定是只能发生在 `tun` 设备创建成功之后才能执行，通常所执行的事情依赖于 `tun` 创建后才能做的事情，而不必与 `preUp` 对应。

2023-03-20 13:08 UTC, xjasonlyu commented on engine/engine.go
> +	preUp(k.TunPreUp)
是的，但我觉得应该放在创建完Stack之后执行。因为stack算是这里的核心了，stack启动失败了似乎也没有必要再post-up了。

不过defer后面确实得确认一下err是否为nil才行

2023-03-20 14:52 UTC, Jackarain commented on engine/engine.go
> +	preUp(k.TunPreUp)
是的，这样可以

2023-03-26 06:39 UTC, xjasonlyu commented
@Jackarain 看看还有一些changes，改完应该就可以merge了

2023-03-27 05:26 UTC, merged

2023-03-27 05:26 UTC, xjasonlyu commented
Merged!